ViewModels/HomeViewModel.cs
using PlayStation_Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PlayStation_Shop.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Product> FavProducts { get; set; }
    }
}

ViewModels/ProductsListViewModel.cs
using PlayStation_Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PlayStation_Shop.ViewModels
{
    public class ProductsListViewModel
    {
        public IEnumerable<Product> AllProducts { get; set; }
        public string CurrCategory { get; set; }

    }
}

ViewModels/ShopCartViewModel.cs
using PlayStation_Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PlayStation_Shop.ViewModels
{
    public class ShopCartViewModel
    {
        public ShopCart ShopCart { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PlayStation_Shop.Data.Interfaces;
using PlayStation_Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PlayStation_Shop.Controllers
{
    public class HomeController : Controller
    {
        private IAllProducts _productRepository;
        
        public HomeController(IAllProducts productRepository)
        {
            _productRepository = productRepository;
        }

        public ViewResult Index()
        {
            var homeCars = new HomeViewModel
            {
                FavProducts = _productRepository.GetFavProducts
            };
            return View(homeCars);
        }
    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using PlayStation_Shop.Data.Interfaces;
using PlayStation_Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PlayStation_Shop.Controllers
{
    public class OrderController : Controller
    {
        private readonly IAllOrders allOrders;
        private readonly ShopCart shopCart;

        public OrderController(IAllOrders allOrders, ShopCart shopCart)
        {
            this.allOrders = allOrders;
            this.shopCart = shopCart;
        }

        public IActionResult CheckOut()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CheckOut(Order order)
        {
            shopCart.ListShopItems = shopCart.GetShopItems();

            if(shopCart.ListShopItems.Count == 0)
            {
                ModelState.AddModelError("", "В корзине нет товаров!"); //ключ и сообщение
            }

            if (ModelState.IsValid)
            {
                allOrders.CreateOrder(order);
                return RedirectToAction("Complete");
            }

            return View(order);
        }

        public IActionResult Complete()
        {
            ViewBag.Message = "Заказ успешно обработан";
            return View();
        }
    }
}

Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using PlayStation_Shop.Data.Interfaces;
using PlayStation_Shop.Data.Models;
using PlayStation_Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PlayStation_Shop.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IAllProducts _allProducts;
        private readonly IProductsCategory _allCategories;


        public ProductsController(IAllProducts iAllProducts, IProductsCategory iProductsCat)
        {
            _allProducts = iAllProducts;
            _allCategories = iProductsCat;
        }

        [Route("Products/List")]
        [Route("Products/List/{category}")]
        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Product> products = null;
            string currCategory = "";
            if (string.IsNullOrEmpty(category))
                products = _allProducts.Products.OrderBy(i => i.Price);

            else if (string.Equals("consoles", category, StringComparison.OrdinalIgnoreCase))
            {
                products = _allProducts.Products.Where(i => i.Category.CategoryName.Equals("Консоли")).OrderBy(i => i.Price);
                currCategory = "Консоли";
            }
            else if (string.Equals("accessories", category, StringComparison.OrdinalIgnoreCase))
            {
                products = _allProducts.Products.Where(i => i.Category.CategoryName.Equals("Аксессуары")).OrderBy(i => i.Price);
                currCategory = "Аксессуары";
            }

            else if (string.Equals("games", category, StringComparison.OrdinalIgnoreCase))
            {
                products = _allProducts.Products.Where(i => i.Category.CategoryName.Equals("Игры")).OrderBy(i => i.Price);
                currCategory = "Игры";
            }

           

            var productObj = new ProductsListViewModel
            {
                AllProducts = products,
                CurrCategory = currCategory
            };

            ViewBag.Title = "Страница с товарами";
            
            return View(productObj);
        }
    }
}

Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Mvc;
using PlayStation_Shop.Data.Interfaces;
using PlayStation_Shop.Data.Models;
using PlayStation_Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PlayStation_Shop.Controllers
{
    public class ShopCartController : Controller
    {
        private IAllProducts _productRepository;
        private readonly ShopCart _shopCart;

        public ShopCartController(IAllProducts productRepository, ShopCart shopCart)
        {
            _productRepository = productRepository;
            _shopCart = shopCart;
        }

        public ViewResult Index() // возвращает определенный шаблон
        {
            var items = _shopCart.GetShopItems();
            _shopCart.ListShopItems = items;

            var obj = new ShopCartViewModel
            {
                ShopCart = _shopCart
            };

            return View(obj);
        }

        //Добавляет товары в корзину и Переадресовывает на другую страницу
        public RedirectToActionResult AddToCart(Guid id)
        {
            var item = _productRepository.Products.FirstOrDefault(i => i.Id == id);
            if(item != null)
            {
                _shopCart.AddToCart(item);
            }
            return RedirectToAction("Index");
        }

    }
}

Views/Home/Index.cshtml
@model HomeViewModel

<h1>Лучшие товары</h1>
<div class="row mt-5 mb-2">
    @{
        foreach (Product product in Model.FavProducts)
        {
            @Html.Partial("AllProducts", product)
        }
    }
</div>

Views/Order/Checkout.cshtml
@model Order

<div>
    <h3>Оформление заказа</h3>
    <form asp-action="Checkout" method="post" class="form-horizontal">
        <div class="form-group">
            <label asp-for="Name"></label>
            <div class="col-md-5">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="SurName"></label>
            <div class="col-md-5">
                <input asp-for="SurName" class="form-control" />
                <span asp-validation-for="SurName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Adress"></label>
            <div class="col-md-5">
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Phone"></label>
            <div class="col-md-5">
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Email"></label>
            <div class="col-md-5">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <input class="btn btn-success" type="submit" value="Завершить заказ"/>
</form>
</div>

Views/Order/Complete.cshtml
<h3>@ViewBag.Message</h3>

Views/Products/List.cshtml
    <h1>Все товары</h1>
    <h3>@Model.CurrCategory</h3>
    <div class="row mt-5 mb-2">
        @{
            foreach (Product product in Model.AllProducts)
            {
                @Html.Partial("AllProducts", product)
            }
        }
    </div>

Views/Shared/AllProducts.cshtml
@model  Product

    <div class="col-lg-4">
        <img class="img-thumbnail" src="@Model.Img" alt="@Model.Name" />
        <h2>@Model.Name</h2>
        <p>@Model.ShortDesc</p>
        <p>Цена: @Model.Price.ToString("c")</p>
        <p><a class="btn btn-warning" asp-controller="ShopCart" asp-action="AddToCart" asp-route-id="@Model.Id">Добавить в корзину</a></p>
    </div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/Style.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a class="navbar-brand" href="/">Playstation Shop</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Products/List">Все товары</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Products/List/consoles">Консоли</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Products/List/accessories">Аксессуары</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Products/List/games">Игры</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/ShopCart">Корзина</a>
                    </li>
                </ul>
                <form class="form-inline mt-2 mt-md-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>
    <div class="container mt-5">
        @RenderBody()
    </div>
    <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>© 2019 Все права защищены · <a href="#">Соглашение</a></p>
    </footer>
    <script src="~/js/bootstrap.min.js"></script>
</body>
</html>

Views/ShopCart/Index.cshtml
@model  ShopCartViewModel
<div class="container">
    @foreach (var el in Model.ShopCart.ListShopItems)
    {
        <div class="alert alert-warning mt-3">
            <b>Товар:</b> @el.Product.Name<br />
            <b>Цена:</b> @el.Product.Price.ToString("c")
        </div> 
    }
    <hr />
    <a class="btn btn-danger mb-5" asp-controller="Order" asp-action="Checkout">Оплатить</a>
</div>